### ISSUE TITLE
Test fails on removal of network interface

### ISSUE THREAD

**Issue by kindkaktus** [pylover/network-interfaces#2] opened 2016-06-22 08:36 UTC
Tests fail for revision ee2d666 or the master branch

```
# python test_interfaces.py
..F
======================================================================
FAIL: test_validate (__main__.NetworkingCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_interfaces.py", line 144, in test_validate
    self.assertRaises(ValidationError, eth0.validate)
AssertionError: ValidationError not raised

----------------------------------------------------------------------
Ran 3 tests in 0.013s

FAILED (failures=1)
```

**Comment by pylover** [comment] 2016-09-21 12:50
Duplicate of #4

**Closed as completed by pylover** 2016-09-21 12:50 UTC
